name: Prettier Linter

on: push

jobs: 
  super-linter: 
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node.js dependencies
        run: npm ci
      - name: run linters
        uses: wearerequired/lint-action@v2
        with: 
          prettier: true
